# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossl < Formula
  desc "GoSSL is a cross platform, easy to use SSL/TLS toolset"
  homepage "https://github.com/yakuter/gossl"
  version "0.1.5"
  license "Apache 2.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yakuter/gossl/releases/download/v0.1.5/gossl_0.1.5_linux_amd64.tar.gz"
      sha256 "016ecf9361d155e663d6eb115c75aaed861f3d220224dfccc5c159781a15dab1"

      def install
        bin.install "gossl"
      end
    end
  end
end
