# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossl < Formula
  desc "GoSSL is a cross platform, easy to use SSL/TLS toolset"
  homepage "https://github.com/yakuter/gossl"
  version "0.1.5"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yakuter/gossl/releases/download/v0.1.5/gossl_0.1.5_macOS_arm64.tar.gz"
      sha256 "a0ae16964e1e7245f8d5b7a495502a4b2de82606a2cb3f317d83a54c7ef15257"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yakuter/gossl/releases/download/v0.1.5/gossl_0.1.5_macOS_amd64.tar.gz"
      sha256 "05b8073a6bca077dce6d926d111edafca47298740ed8a142afb579a3d05f1603"

      def install
        bin.install "gossl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yakuter/gossl/releases/download/v0.1.5/gossl_0.1.5_linux_arm64.tar.gz"
      sha256 "1499b8547ab859b452d890465913d5d37349c730512d3ea35a5aa54007acb3d9"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yakuter/gossl/releases/download/v0.1.5/gossl_0.1.5_linux_amd64.tar.gz"
      sha256 "49d7c5cf7c6e1caf83b6fd9736e793fe56707dd7a9eb58bcd9f348d7688f8895"

      def install
        bin.install "gossl"
      end
    end
  end
end
